- name: test composite 
  on:
    push

  jobs:

    steps:
    - name: Setup Maven Action
      uses: poc/setup-maven-action@v1
      with:
        java-version: 9
        maven-version: 3.8.4
  
    - name: Build with Maven
      run: mvn verify