---
name: test composite 
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Setup Maven Action
        uses: poc/setup-maven@v1
        with:
          java-version: 9
          maven-version: 3.8.4
    
      - name: Build with Maven
        run: mvn verify